stages:          # List of stages for jobs, and their order of execution
  - test

unit-test-job:
  stage: test
  script:
    - sudo apt-get install openjdk-17-jdk -y
    - cd Lab2/tester-linux-x64
    - chmod 777 ./http-server-tester
    - ./http-server-tester run --mode basic
  tags:
    - cloud-compute
